version: '3'
services:
    postgres:
        image: 'postgres:10.5'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - '3050:80'
    api:
        depends_on:
            - postgres
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - /d/DEVELOP/docker-tutorial/complex/server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        stdin_open: true
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - /d/DEVELOP/docker-tutorial/complex/client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        volumes:
            - /app/node_modules
            - /d/DEVELOP/docker-tutorial/complex/worker:/app
    